### ISSUE TITLE
Add option in UI to set the points for each question

### ISSUE THREAD

**Issue by katsanjib046** [IonMich/instructor_pilot#34] opened 2023-01-10 23:41 UTC
Currently, each question gets one point, so for n points there will be n questions. This needs to be fixed so that user can choose points for each questions. This function needs to be added in the UI for all users (right now it works for admin only). It should be added as a preference for each assignment group and implemented such that if it is set for one assignment, it is set for the entire assignment group.

**Comment by IonMich** [comment] 2023-01-11 23:42
Actually that's a duplicate of #21

**Closed by IonMich** 2023-01-11 23:42 UTC
Labels: duplicate, enhancement
