### ISSUE TITLE
File Upload as a comment

### ISSUE THREAD

**Issue by katsanjib046** [IonMich/instructor_pilot#23] opened 2022-09-17 02:42 UTC
The file doesn't seem to upload below the comment section. Even if it did, it's not visible to the user.

**Comment by IonMich** [comment] 2022-09-17 04:09
Good catch Sanjib! There are two issues there that need to be fixed:

- [ ] Submitting the form with a comment upload does not actually update the `comment_files` field of the submission, i.e. the file is not uploaded to the database. This can be verified by looking at the admin entry for the corresponding submission.
- [ ] Previously uploaded comment_files are not visible in the UI, unlike what happens for previously uploaded comments.

The cause of the first issue is that the property `enctype` of the `<form>` element in `submissions/templates/submissions/detail.html` needs to be set to `"multipart/form-data"`, according to [this](https://stackoverflow.com/questions/12158837/how-to-extract-file-object-from-django-form-filefield) SO post. I made this change and now this works, i.e. the file is visible in the admin entry for the submission.

In order to handle the second one would write to add this to the `detail.html` page, in a very similar way to how past comments are being handled in `detail.html`. We could add a section for past files, which includes the filename, and ideally includes a hyperlink to the actual file. Let me know if you would like to push corrections add I will assign this to you. Otherwise I can try to fix this in the not so distant future.

**Comment by katsanjib046** [comment] 2022-09-17 16:00
Alright, I will handle the second issue then. Thanks for fixing the first issue.

**Closed** 2023-01-11 05:55 UTC
Labels: bug, good first issue
